---
# This will install nagios

- name: install nagios
  yum: pkg={{ item }} state=present
  with_items:
   - nagios
   - nagios-plugins
   - nagios-plugins-nrpe
   - nagios-plugins-ping
   - nagios-plugins-ssh
   - nagios-plugins-http
   - nagios-plugins-mysql
   - nagios-devel
   - nagios-plugins-load
   - nagios-plugins-users
   - nagios-plugins-disk
   - nagios-plugins-swap
   - nagios-plugins-procs
   - nagios-plugins-tcp
  notify: restart httpd

- name: create nagios config dir
  file: path=/etc/nagios/ansible-managed state=directory

- name: configure nagios
  copy: src=nagios.cfg dest=/etc/nagios/nagios.cfg
  notify: restart nagios

- name: configure commands
  copy: src=commands.cfg dest=/etc/nagios/objects/commands.cfg
  notify: restart nagios

- name: configure templates
  copy: src=templates.cfg dest=/etc/nagios/objects/templates.cfg
  notify: restart nagios


- name: configure localhost monitoring
  copy: src=localhost.cfg dest=/etc/nagios/objects/localhost.cfg
  notify: restart nagios

- name: configure localhost monitoring
  copy: src=mysql.cfg dest=/etc/nagios/objects/mysql.cfg
  notify: restart nagios

- name: configure nagios services
  copy: src=ansible-managed-services.cfg dest=/etc/nagios/

- name: Create spool directory
  file:
      dest: /var/log/nagios/spool/checkresults
      state: directory
      owner: nagios
      group: nagios

- name: create the nagios object files
  template: src={{ item + ".j2" }}
            dest=/etc/nagios/ansible-managed/{{ item }}
  with_items:
    - webservers.cfg
    - dbservers.cfg
  notify: restart nagios

- name: start nagios
  service: name=nagios state=started enabled=yes
