- name: Reboot OS
  shell: /usr/sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: True

- name: Pause for 1 min
  pause:
    minutes: 1

- name: Wait fot Host
  wait_for_connection:
    delay: 30
    timeout: 120

- name: get Uptime
  shell: /usr/bin/uptime
