
- name: Check if OS is CentOS/RedHat 6
  include: centos6-setup.yml
  when: ((ansible_os_family != "RedHat") or (ansible_distribution_major_version|int == 6))

- name: Check if OS is CentOS/RedHat 7
  include: centos7-setup.yml
  when: ((ansible_os_family != "RedHat") or (ansible_distribution_major_version|int == 7))

- name: Install apache
  yum: name={{ item }} state=present
  notify:
    - restart apache
  with_items:
      - httpd
      - mod_ssl
      - libselinux-python
