# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

    config.vm.define "web" do |web|
        web.vm.box = "bento/centos-7.2"
        web.vm.hostname = "wordpress"
        web.vm.network "private_network", ip: "192.168.10.100"
        web.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yaml"
        end
        web.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.cpus = 1
            vb.name = 'wp_app'
            vb.customize ["modifyvm", :id, "--memory", "256"]
            vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
       end
    end

    config.vm.define "mon" do |mon|
        mon.vm.box = "bento/centos-7.2"
        mon.vm.hostname = "nagios"
        mon.vm.network "private_network", ip: "192.168.10.101"
        mon.vm.provision "ansible" do |ansible|
            ansible.playbook = "nagios.yaml"
        end
        mon.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.name = 'wp_nagios'
            vb.cpus = 1
            vb.customize ["modifyvm", :id, "--memory", "256"]
            vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
       end
    end





    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--memory", "256"]
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
   end
end
